@patch.object(jenkins.Jenkins, 'jenkins_open')
def test_failed(self, jenkins_mock):
    jenkins_mock.side_effect = [jenkins.NotFoundException(), None, jenkins.NotFoundException()]
    with self.assertRaises(jenkins.JenkinsException) as context_manager:
        self.j.create_job(u'TestJob', self.config_xml)
    self.assertEqual(jenkins_mock.call_args_list[0][0][0].get_full_url(), self.make_url('job/TestJob/api/json?tree=name'))
    self.assertEqual(jenkins_mock.call_args_list[1][0][0].get_full_url(), self.make_url('createItem?name=TestJob'))
    self.assertEqual(str(context_manager.exception), 'create[TestJob] failed')
    self._check_requests(jenkins_mock.call_args_list)
