{
  try {
    newWithCause(exceptionClass,new Exception());
    return true;
  }
 catch (  Exception e) {
    return false;
  }
}
