{
  if (!m_done.get())   try {
    susceptibleRun();
  }
 catch (  Exception e) {
    throw loggedException(e,"Fault occured while executing runnable");
  }
}
