@patch.object(jenkins.Jenkins, 'jenkins_open')
def test_in_folder_failed(self, jenkins_mock):
    jenkins_mock.side_effect = [None, jenkins.NotFoundException()]
    with self.assertRaises(jenkins.JenkinsException) as context_manager:
        self.j.copy_job(u'a Folder/TestJob', u'a Folder/TestJob_2')
    self.assertEqual(jenkins_mock.call_args_list[0][0][0].get_full_url(), self.make_url('job/a%20Folder/createItem?name=TestJob_2&mode=copy&from=TestJob'))
    self.assertEqual(str(context_manager.exception), 'create[a Folder/TestJob_2] failed')
    self._check_requests(jenkins_mock.call_args_list)
