{
  return new CancellationException("Future.cancel() was called.");
}
